export const ASIDE_SWITCH = 'ASIDE_SWITCH'
export const USER_INFO_GET = 'USER_INFO_GET'
export const USER_INFO_SAVE = 'USER_INFO_SAVE'
export const ADD_MEETING_NUM_SAVE_DEL = 'ADD_MEETING_NUM_SAVE_DEL'

// 登录
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_OUT_LOGIN = 'USER_OUT_LOGIN'
